name: 'Styled wotd'
description: 'Create styled Word of the Day by language and input color parameters'
author: 'AlexRogalskiy'

inputs:
  language:
    description: 'language of the word'
    required: false
    default: 'random'
  pattern:
    description: 'word image background pattern'
    required: false
    default: 'random'
  width:
    description: 'word image width'
    required: false
    default: '100%'
  height:
    description: 'word image height'
    required: false
    default: '100%'
  backgroundColor:
    description: 'word image background color'
    required: false
    default: '%23FFFFFF'
  fontColor:
    description: 'word image font color'
    required: false
    default: '%230A83DC'
  opacity:
    description: 'word image background opacity'
    required: false
    default: '0.3'
  colorPattern:
    description: 'word image text color'
    required: false
    default: '%23FFE0E9'
  name:
    description: 'word image name'
    required: false
    default: 'word'
  path:
    description: 'word image path'
    required: false
    default: 'images'

outputs:
  image:
    description: 'word image generated by input parameters'

runs:
  using: 'node12'
  main: 'dist/index.js'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'image'
  color: 'green'
